# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
   config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     config.disksize.size = "20GB" 
   end
   config.vm.provision "shell", path: "/Users/joseantoniosanchezmenor/Vagrant/centos7/bootstrap.sh"	
end
